Encoding.default_external = "UTF-8"
source 'https://supermarket.chef.io'

metadata

cookbook 'conda', github: "hopsworksjenkins/conda-chef", branch: "128-ee"
cookbook 'kagent', github: "hopsworksjenkins/kagent-chef", branch: "128-ee"
cookbook 'hops', github: "hopsworksjenkins/hops-hadoop-chef", branch: "128-ee"
cookbook 'ndb', github: "hopsworksjenkins/ndb-chef", branch: "128-ee"
cookbook 'hadoop_spark', github: "hopsworksjenkins/spark-chef", branch: "128-ee"
cookbook 'flink', github: "hopsworksjenkins/flink-chef", branch: "128-ee"
cookbook 'livy', github: "hopsworksjenkins/livy-chef", branch: "128-ee"
cookbook 'drelephant', github: "hopsworksjenkins/dr-elephant-chef", branch: "128-ee"
cookbook 'epipe', github: "hopsworksjenkins/epipe-chef", branch: "128-ee"
cookbook 'tensorflow', github: "hopsworksjenkins/tensorflow-chef", branch: "128-ee"
cookbook 'dela', github: "hopsworksjenkins/dela-chef", branch: "128-ee"
cookbook 'kzookeeper', github: "hopsworksjenkins/kzookeeper", branch: "128-ee"
cookbook 'kkafka', github: "hopsworksjenkins/kafka-cookbook", branch: "128-ee"
cookbook 'elastic', github: "hopsworksjenkins/elasticsearch-chef", branch: "128-ee"
cookbook 'hopslog', github: "hopsworksjenkins/hopslog-chef", branch: "128-ee"
cookbook 'hopsmonitor', github: "hopsworksjenkins/hopsmonitor-chef", branch: "128-ee"
cookbook 'hops_airflow', github: "hopsworksjenkins/airflow-chef", branch: "128-ee"
cookbook 'hive2', github: "hopsworksjenkins/hive-chef", branch: "128-ee"
cookbook 'consul', github: "hopsworksjenkins/consul-chef", branch: "128-ee"
cookbook 'ulimit', github: "hopsworksjenkins/chef-ulimit", branch: "128-ee"
cookbook 'glassfish', github: "hopsworksjenkins/chef-glassfish", branch: "128-ee"
